#cloud-config
preserve_hostname: false
hostname: docker-host1
runcmd:
  - "userdel -r packer"
  - "chmod 777 /data"
disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: data-disk
    filesystem: ext4
    device: '/dev/sdb1'
    overwrite: false

mounts:
  - ["sdb", "/data", "auto"]
