#cloud-config
preserve_hostname: false
hostname: pve1-docker-host1
timezone: America/Los_Angeles
ssh_pwauth: false
runcmd:
  - "chmod 777 /data"
disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: data-disk
    filesystem: ext4
    device: '/dev/sdb1'
    overwrite: false

mounts:
  - ["sdb", "/data", "auto"]

write_files:
  - path: /etc/docker/daemon.json
    content: |
      {
        "data-root": "/data/docker"
      }
    owner: root:root
    permissions: '0644'